language: scala
sudo: false
scala:
- 2.12.12
- 2.13.3
dist: xenial
jdk:
- openjdk8
script:
- sbt "++${TRAVIS_SCALA_VERSION}! -v" test
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
  - name: dotty
    script:
    - sbt "project knockoffJVM" "++ 0.26.0-RC1!" test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
