name: scala-steward
on:
  push:
  schedule:
  - cron: '0 0 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
    - name: Launch Scala Steward
      if: ${{ github.repository_owner == 'foundweekends' }}
      uses: scala-steward-org/scala-steward-action@v2.9.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
